name: PR title check
on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  title-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^((,?\s?([a-zA-Z0-9])+-\d{1,5})+)?:.*$' # Regex the title should match.
          min_length: 10 # Min length of the title
          max_length: 150 # Max length of the title
